### ISSUE TITLE
对$it->setIteratorRow(650);这行代码不太理解，请指教！

### ISSUE THREAD

**Issue by 775467383** [crazyhl/php_jump_auto#2]
你好，请问这行代码中$it->setIteratorRow(650);的setIteratorRow方法是什么意思呢？上次题主说，是根据自己手机截图选了一个合适的点位，但一个点位不是应该由行和列或者是x，y坐标的值来确定？650意思是像素的第650行吗？因为网上和官网的这个方法使用案例都比较少，所以小白不太明白，麻烦解释一下这个方法的作用，还有这个650代表的含义，谢谢你！

**Comment by crazyhl** [comment]
setIteratorRow 就是把遍历图片的迭代器设置到指定的行。其实我的代码里面也是设置到了列的坐标的。再哪行代码的后面两行，就是，getCurrentIteratorRow 这个代码的意思是获取那一行的所有列的数据，然后 $pixels[650]->getColor(); 利用这个再第650列 获取了颜色。
